### ISSUE TITLE
How to check TFT firmware already flashed

### ISSUE THREAD

**Issue by ahmadkarlam** [dgtaheno/artillery-Genius#12]
Hi, I bought second hand Artillery Genius and I want flash to newer marlin firmware. Is there any way to know that TFT firmware already flashed or not so I don't have to open back cover of my 3d print ?

**Comment by dgtaheno** [comment]
Hello,
welcome onboard to Artillery Genius community.

You can check your TFT Firmware version by:

Menu-->Settings-->Info

![1 -menu](https://github.com/dgtaheno/artillery-Genius-Marlinfw/assets/62843933/51bd6d5b-b442-4bde-9052-bdb825d7435a)
![2 -settings](https://github.com/dgtaheno/artillery-Genius-Marlinfw/assets/62843933/71b3e6f5-397a-4792-82d5-1b0028371616)
![3 -info](https://github.com/dgtaheno/artillery-Genius-Marlinfw/assets/62843933/354f7307-423b-4780-96ae-bb9c7a6e9bda)
![4 -FW version](https://github.com/dgtaheno/artillery-Genius-Marlinfw/assets/62843933/57aebb3c-bf59-4172-bd1d-870a7a822aef)

**Comment by ahmadkarlam** [comment]
Thanks, I already done update firmware and its amazing. Great work @dgtaheno

**Comment by dgtaheno** [comment]
Thank you for your feedback!appreciate that you are enjoying it!
