### ISSUE TITLE
No Linear advance option

### ISSUE THREAD

**Issue by HittyStorm** [dgtaheno/artillery-Genius#15]
There is no Linear advance enabled in "Marlin.2.1.2.1.hex"
I send "M900" and get "unknown"...

**Comment by dgtaheno** [comment]
Hello,
I prepared a firmware version with Linear Advance activated:
https://github.com/dgtaheno/artillery-Genius-Genius_Pro-X1-Marlinfw/blob/27cbb9dc35a9d679c6411ed637d918a25885ffb5/Marlin%202.1.2.1-la.hex

Please give it a try, if it works fine I will leave this FW version as the good one.

Best regards.
