### ISSUE TITLE
Failed to enable BLTouch

### ISSUE THREAD

**Issue by jorgermp** [dgtaheno/artillery-Genius#16]
Hi,

I installa the last firmware 2.1.2.1 with BLTouch support, but when the printer start have this message "Failed to enable BLTouch"
I attach a video, could you help me?

https://github.com/dgtaheno/artillery-Genius-Genius_Pro-X1-Marlinfw/assets/1401249/caff51a7-f598-4bcd-98a3-67c5338d2f66

**Comment by dgtaheno** [comment]
Hello @jorgermp ,
for 2.1.2.1 with BLTouch I understand that you refer to:

Artillery Genius BLTouch
[[https://github.com/dgtaheno/artillery-Genius-Genius_Pro-X1-Marlinfw/blob/Marlin-2.1.2.1/Marlin%202.1.2.1_BLT.hex]
](https://github.com/dgtaheno/artillery-Genius-Genius_Pro-X1-Marlinfw/blob/c8530a38b4bd09183c6fbc336bb6e5accd1c38ac/Marlin%202.1.2.1_BLT.hex)

If this is the case, I have revised the file and compared once again with the example from MarlinFW, just corrected a couple of parameters and created this new Firmware version:

https://github.com/dgtaheno/artillery-Genius-Genius_Pro-X1-Marlinfw/blob/c8530a38b4bd09183c6fbc336bb6e5accd1c38ac/Marlin%202.1.2.1_BLT_corrections_pending%20on%20validation.hex

Could you please give it a try and inform if it works ok?

Unfortunately I have no BLT touch to test it :-(

Thank you in advance for your support and bringing up the issue.

Best regards.
