### ISSUE TITLE
Movement during filament change

### ISSUE THREAD

**Issue by saddleau** [dgtaheno/artillery-Genius#19]
I have seen the problem with my printer that when I am unloading/loading filament after a filament runout has occurred, it is extremely difficult to keep the X axis from moving while fiddling with the extruder. The printer assumes it has not and continues the print from the wrong location. 
It would be nice if the printer did an X axis homing and then then returned to the print location after completing the change. Y and Z axis are not affected during a filament change.

**Comment by dgtaheno** [comment]
Hello @saddleau ,

Hope that you are doing good.

Quick question, are you printing from SD card or from other source like Octoprint?

Additionally, which firmware version are you working with?

<img width="672" alt="Screenshot 2023-12-17 085305" src="https://github.com/dgtaheno/artillery-Genius-Genius_Pro-X1-Marlinfw/assets/62843933/4ef65e56-7a4d-42eb-84e4-770fb8faf5d7">

Best regards.

**Comment by saddleau** [comment]
I am printing from USB stick, not SD card or USB port on firmware 2121Pro. I have corrected the printer's terrible Z banding by some changes to the extruder, but now I find loading filament hard to do without moving the whole hotend slightly on the X axis. I don't currently see an issue with rehoming it on the X axis so the printer can relearn where the hotend is again before resuming.

**Comment by dgtaheno** [comment]
Hello @saddleau ,

Sorry for taking that long to answer you, as you have modified the extruder, this might affect the x position.

I´d try adding some code in the slicer at the beginning defining the right X home by this parameter:

https://marlinfw.org/docs/gcode/M206.html#:~:text=M206%20%2D%20Set%20Home%20Offsets&text=Use%20M206%20to%20apply%20a,the%20new%20home%20offset%20values.

I´d also try with this command:

https://marlinfw.org/docs/gcode/G028.html

As it is a customized machine I´ll not consider this topic as an issue with the fw, it is most likely an issue with the fw with this specific machine.

Good luck.
