### ISSUE TITLE
TFT Zip File Invalid?

### ISSUE THREAD

**Issue by ultradave9000** [dgtaheno/artillery-Genius#20]
I've downloaded the TFT file but I cannot extract it's contents - both 7Zip and Windows report the file as invalid.  Have re-downloaded multiple times.  Has the hosted filed become corrupt?

**Comment by dgtaheno** [comment]
It is strange man, just tried and it is working for me
<img width="565" alt="Screenshot 2023-12-17 084243" src="https://github.com/dgtaheno/artillery-Genius-Genius_Pro-X1-Marlinfw/assets/62843933/d8ff1d14-4764-4356-9b02-c30b3a06ca4d">
Maybe it is a problem you have with zip?

**Comment by ultradave9000** [comment]
Ah, thanks for checking.  Realised it was how I was downloading it - 'Save Link As' doesn't actually download the zip file (like it did the hex files) - weird.
