### ISSUE TITLE
Provide configuration.h and configuration_adv.h

### ISSUE THREAD

**Issue by DavidTre07** [dgtaheno/artillery-Genius#21]
Hi there,
as I made some updates on my printer (TMC2208) could you provide us the configuration.h and configuration_adv.h you created for this printer? So I could adapt it to my configuration and recompile it.

Thanks,
Regards.

**Comment by tom-walkr** [comment]
I second this, it would be really helpful to be get access to the source files so that additional modifications can be made.

**Comment by dgtaheno** [comment]
Hi,
sure you can take the configurations directly from Marlin:

https://github.com/MarlinFirmware/Configurations/tree/release-2.1.2.1/config/examples/Artillery

From there you can customize anything you need.

Best regards.
