### ISSUE TITLE
BLTouch X1

### ISSUE THREAD

**Issue by ioFantasma** [dgtaheno/artillery-Genius#22]
Hello, thanks for the contribution, it will be possible to enable bltouch for the X1.

**Comment by dgtaheno** [comment]
Hello @ioFantasma ,

Just compiled it, here you have it:

[https://github.com/dgtaheno/artillery-Genius-Genius_Pro-X1-Marlinfw/blob/fd9bab2cd219115b90131ca917cf7c1cb03addc4/Marlin%202.1.2.1-X1-BLT.hex](https://github.com/dgtaheno/artillery-Genius-Genius_Pro-X1-Marlinfw/blob/fd9bab2cd219115b90131ca917cf7c1cb03addc4/Marlin%202.1.2.1-X1-BLT.hex) .
Please let me know if any issue.

Best regards.

**Comment by ioFantasma** [comment]
Hi, tnks !! =)
