### ISSUE TITLE
Marlin 2.1.2.1_BLT

### ISSUE THREAD

**Issue by Dexternaitor** [dgtaheno/artillery-Genius#25]
Hi,
I have installed your firmware. I'm very happy with it, but you have limited the temp to 260º and I need to print at 290º.
Please, can you tell me how to set the temp max to 290º? 
I tried to find the config file, but only found the .hex and I don't know how to work with .hex.

**Comment by dgtaheno** [comment]
Hello,
 I have compiled a version considering 295 C max hotend temp, please note that if your printer is not prepared for that it can damage it going to these high temp.

[Marlin fw BLT-295C](https://github.com/dgtaheno/artillery-Genius-Genius_Pro-X1-Marlinfw/blob/a71e80a30e41934ef811bd6a04cabd763868d586/Marlin%202.1.2.1_BLT-295C.hex)

Please let me know if it works well.

Best regards.
