### ISSUE TITLE
Problem with bedsize on Artillery Genius

### ISSUE THREAD

**Issue by piunch** [dgtaheno/artillery-Genius#29]
Hi,

Thanks for your efforts on updating Marlin Firmware for Artillery Genius.
I recently upgraded my Artillery firmware with Bltouch variant and I am having some issues regarding the bedsize and the Y offset.

When moving the bed (Y axe) to the front, the boundary does not seem to be clear and the stepper motor does a grinding sound.
I think that this might be related with the **Y_BED_SIZE** parameter as in Configuration.h it looks like this:

```
define Y_BED_SIZE 230
``` 
As far as I know, I thought that Artillery Genius had a 220mm bed size. Can this be an error?

And if this is correct, do you know how can I solve this behaviour?

Thanks in advance!

**Comment by piunch** [comment]
As you can see in the original firmware from Artillery, bed_size values are 220mm.

https://github.com/artillery3d/genius-firmware/blob/716d73ecc614487c5ebdefd2f6236834ac66bf7f/Marlin/Configuration.h#L881

**Comment by ChrizZz90** [comment]
facing the same issue

**Comment by fjherna** [comment]
facing the same issue 

:)

Javier

**Comment by dgtaheno** [comment]
Hi guys,

just adjusted the .hex for artillery genius BL-T, considering define Y_BED_SIZE 220 in configuration.h

You will find the corrected file here:

https://github.com/dgtaheno/artillery-Genius-Genius_Pro-X1-Marlinfw/blob/4d83c20d5f05282cbfde12e74f0bc1e2c0c36fde/Marlin%202.1.2.1_BLT_corrections_pending%20on%20validation_180424.hex

Please let me know if it works ok so I can replace the original file with this one.

Best regards.

**Comment by fjherna** [comment]
Hi dgtaheno,

Thanks for your effort in solving the bed issue.

Unfortunately I can not test that version of the Firmware because my Artillery Genius holds a different Extruder (Trianglelab MATRIX) and Thermistor. I modified and created my own Firmware 2.1.2.1 which includes BL-T and it is working correctly.

When I reported the problem with that issue I had the original Artillery Genius Extruder and thermistor.

Kind regards,

Javier

**Comment by ChrizZz90** [comment]
made a first test, Looks like it works, thanks @dgtaheno

**Comment by dgtaheno** [comment]
> made a first test, Looks like it works, thanks @dgtaheno 

Glad that it works!enjoy it!

**Comment by fjherna** [comment]
Beside that my Artillery Genius holds different hardware (Extruder and Thermistor), I though it would not affect the normal functions.
Therefore I have done a test of the new Firmware with my artillery genius BL-T, and I consider that the Y_BED_SIZE 220 issue is fixed.

thanks @dgtaheno

**Comment by dgtaheno** [comment]
> Beside that my Artillery Genius holds different hardware (Extruder and Thermistor), I though it would not affect the normal functions.
> 
> Therefore I have done a test of the new Firmware with my artillery genius BL-T, and I consider that the Y_BED_SIZE 220 issue is fixed.
> 
> 
> 
> thanks @dgtaheno

Thank you for your feedback!!
