### ISSUE TITLE
TFT Firmware files CUR vs BIN extension

### ISSUE THREAD

**Issue by micovery** [dgtaheno/artillery-Genius#3]
I tried updating the TFT firmware using the provided files. But, it was not working. After some troubleshooting I change the file extension from CUR to BIN, and was able to get it work.

MKSTFT28.CUR to MKSTFT28.BIN

**Comment by alfem** [comment]
Yes, I confirm that.

**Comment by dgtaheno** [comment]
zip updated in https://github.com/dgtaheno/artillery-Genius/commit/fa3913267e5d73a7ad21b2301abfef5166633557 changing  , MKSTFT28.CUR to MKSTFT28.BIN.
I´ll mark as completed, please feel free to reopen if it is not a fix.
