### ISSUE TITLE
TFT firmare Genius pro

### ISSUE THREAD

**Issue by lello194** [dgtaheno/artillery-Genius#31]
Hi, I'm installing your Fw, but I can't update the TFT . I have tried to upload the original TFT firmware and it work. For this I can't do.  Obviously I have unzip it and paste it in the root of the SD card.

**Comment by rcaruso82** [comment]
Hello, please check if you have a TFT screen with the GD chipset, if so you need to use another TFT firmware for example:

https://dave811.github.io/ATSG/installation/

Best regards!

**Comment by dgtaheno** [comment]
@rcaruso82 Thank you for answering!

Best regards!
