### ISSUE TITLE
Artillery Genius Pro - info

### ISSUE THREAD

**Issue by Eldenroot** [dgtaheno/artillery-Genius#5]
Hi, I got my new printer - Artillery Genius Pro.

I wanna change the stock firmware. So I have found this one from you.

So you keep this firmware updated? Any milestone or planned features? Or whatever you recommend?

**Comment by Eldenroot** [comment]
I mean new update of Merlin integrated to this firmware?

**Comment by dgtaheno** [comment]
> Hi, I got my new printer - Artillery Genius Pro.
> 
> 
> 
> I wanna change the stock firmware. So I have found this one from you.
> 
> 
> 
> So you keep this firmware updated? Any milestone or planned features? Or whatever you recommend?

Hello Eldenroot,

Thank you for your interest in this repo for Artillery Genius Marlin firmware.

I'm maintaining the repo yes, not as good as I would like, but I am doing it.

In the other hand, please note that this Marlin firmware it is only for artillery Genius, not for the PRO, which has a different and not compatible firmware.

Unfortunately I own a Genius so, I'm only customizing the firmware for the Genius as I have not the hardware to test other firmware.

Please do not install this firmware in your artillery genius pro as it is expected not to work and create issues with your printer.

I encourage you to make your own customization, following online manuals it is not complicated.

If you need to contact me feel free to mail me dgtaheno@hotmail.com

Best regards.
