### ISSUE TITLE
Do you really need to open device to flash?

### ISSUE THREAD

**Issue by Austin1** [dgtaheno/artillery-Genius#8]
I used this version and guide and was able to install TFT and firmware without any opening of my device, however, I like how you have your project organized in a Git repo and would like to contribute here vs that Thingiverse page...
https://www.thingiverse.com/thing:5186707

I also like the checklist provided here for post-install calibration, maybe we could weave these into the Readme.MD? I've been battling my GeniusPro for about a week trying to get it calibrated and some straight forward post-install steps would be awesome for newbies.

Here is a pretty messy checklist from that other page.

> -ALWAYS put a thin sheet of paper to prevent the nozzle from crashing into the bed. The values have been increased and deemed as “safe” but I won’t take any responsibility for any damages caused by these files. I have tested it several times + have a beta-tester that is helping me, but it is better to be safe than sorry.
> -After the flash start with Homing all axes – homes fine and doesn’t crash into the bed ? Move on.
> -do the PID Tuning
> -preheat nozzle and bed to the target temp of your liking
> -Go into Movement – Leveling – and set the “P offset” – I do this till the nozzle is just before slightly scratching the surface of the paper. Please keep in mind that I put the paper only under the nozzle – not under the BLtouch sensor.
> -do the rest of the calibration steps --- e.g. steps per mm, UBL.
> -after doing UBL make sure you turn BL on (in the same menu as UBL -- BL : on is displayed)
> -make sure you save everything to EEProm
> -start printing and be ready to fine-tune your first layer with the “Babystepping” – do it in small increments. Do not forget to save afterwards.
> -Done! Enjoy your prints!
> Oh... you may also want to tweak Linear advance. Current k value is 0.13 but if you switched the nozzle or heatbreaker you may be nearer to 0.05 rather than 0.13 :-)
> 
> Last but not least ---- support will be available and I will check the comments daily and I will "try" to help you out, but I need to repeat it clearly --- you are doing it on your own responsibility and I won't accept any blame if something goes wrong. For me it works perfectly.
> You need a little bit of knowledge in any case -- flashing --- a little,
> --if you want to modify the source -- a lot more,
> --You NEED to use Visual Studio Code with PlatformIO Extension to compile. Forget about ArduinoIDE, PERIOD. If you don't know how to use MS VSC + Platformio and how to set it up - before starting to ask questions here - LEARN from various YT tutorials. I am not here to school you through VSC.
> 

If I follow this and it actually works, i'd be happy to clean up and add to your ReadMe. 

I tried a bunch of this and failed pretty miserably at getting a decent print, so I just did a full EEPROM factory reset and I'm now attempting the above checklist. Currently on step 2, PID tuning.

**Comment by dgtaheno** [comment]
Hello @Austin1 ,

Thanks a lot for stopping by and glad the way the project is documented here in GitHub.

I do really appreciate the time you took preparing the comment.

I had a look on this Thingiverse page and I realized that the firmware is referring to Artillery Genius Pro and X2, while the software considered here works only for Artillery Genius(The old model).

Please do not install my firmware an Artillery Genius Pro or X2 it will not probably work and might cause damage to the printer as it is not intended for these models.

In the other hand, as far as I know original Artillery Genius(Not the PRO) TFT firmware does not allows you to update the firmware without opening the printer...(maybe I´m wrong...), but in the other hand as you mentioned maybe the new Artillery Genius PRO is coming with the new Big TreeTech TFT Firmware which allows you to do the updated without opening the printer, as you mentioned in that case or when people are updating the TFT, each new update can be installed without the need of opening the printer.

I know that calibrating a printer once you are new to 3D printing is not an easy task(believe me I have gone through this :-)), I do highly recommend you checking https://artillery.n3t.ro/setup.html it was really helpful for me when I started with my printer, hopefully this will also help you.

I find really interesting your proposal on the calibrations, but honestly I think that there are other places where it is explained in more depth and is more useful like the link I put in the usage section of README.md

If you find further problems, please feel free to contact me and I´ll be glad to support you, even if this software was not intended for the Genius PRO, I don´t think that it will be too different from this software.

Best regards.
David
